---
apiVersion: v1
kind: Service
metadata:
  name: c270-assignment-service
spec:
  type: NodePort
  selector:
    tier: c270-assignment-front-end
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30009
